//! Grid mesh (jittered grid). Data only; generation (jittered points, Delaunay,
//! Voronoi, repacking) lives in `vor-import`.

use crate::cells::GridCells;
use crate::feature::Feature;
use crate::voronoi::VoronoiVertices;

/// Grid mesh — the stage before repacking.
///
/// The `points` are the jittered points in row-major order (`y` outer, `x` inner),
/// in the exact order `getJitteredGrid` produces in Azgaar (`graphUtils.ts:46-98`).
/// Cell `id` `k` corresponds to `points[k]` → this is the detail that makes the
/// correspondence between RNG (jitter consumption order) and per-cell attributes
/// deterministic (see `docs/phases/phase-0-research.md` §6.5, §13.4).
/// The `boundary` are virtual points outside the canvas to avoid infinite Voronoi
/// cells at the edge — they do not consume RNG (§6.6).
#[derive(Debug, Clone, Default, serde::Serialize, serde::Deserialize, PartialEq)]
pub struct Grid {
    /// Desired cell count (user input; 10000 default in Azgaar).
    pub cells_desired: u32,
    /// Spacing between points = `min(width, height) / sqrt(cellsDesired)`, rounded down to int.
    pub spacing: f32,
    /// Number of columns = `floor(width / spacing)`.
    pub cells_x: u32,
    /// Number of rows = `floor(height / spacing)`.
    pub cells_y: u32,
    /// Canvas width (Azgaar units — the `graphWidth` of header slot `[0]`).
    pub width: f32,
    /// Canvas height (Azgaar units — the `graphHeight` of header slot `[0]`).
    pub height: f32,
    /// Jittered points (`points.length = cells_x * cells_y`), row-major.
    pub points: Vec<[f32; 2]>,
    /// Virtual boundary points (do not consume RNG). Concatenated to `points` before
    /// Delaunay: `allPoints = points.concat(boundary)`.
    pub boundary: Vec<[f32; 2]>,
    /// Voronoi topology (regenerated by `vor-import`).
    pub cells: GridCells,
    /// Voronoi vertices (regenerated by `vor-import`).
    pub vertices: VoronoiVertices,
    /// Grid features (`grid.features` — slot `[6]` carries them; the pre-repack version).
    pub features: Vec<Feature>,
}

impl Grid {
    /// Number of real points (without `boundary`). Each one = 1 jittered cell.
    #[inline]
    pub fn points_n(&self) -> usize {
        self.points.len()
    }

    /// Total number of points used in Delaunay: real + boundary.
    #[inline]
    pub fn all_points_n(&self) -> usize {
        self.points.len() + self.boundary.len()
    }
}
