//! Pack mesh — the result of the grid→pack repacking.
//!
//! The repacking (algorithm `reGraph` in Azgaar's `public/main.js:1157-1209`) discards
//! unnecessary cells (non-coastal deep ocean, certain non-coastal lakes) and adds
//! extra points on coasts (midpoint between neighboring cells of the same type at ≥ spacing
//! distance). Then it recomputes Delaunay/Voronoi over those points (`calculateVoronoi`).
//!
//! Critically: if Voronia produces a different pack mesh (even by 1 cell or by a
//! different ordering in `newCells.p`), the `pack.cells.g[packId] → gridId` mapping ends
//! up different, and all the attributes Azgaar serializes indexed by pack id
//! (biome, state, burg, ...) get applied to the wrong cells — **a silent bug with no
//! runtime error**. That is why the repacking in `vor-import` must be bit-exact.

use crate::cells::PackCells;
use crate::feature::Feature;
use crate::voronoi::VoronoiVertices;

/// Pack mesh — the mesh most of the simulation operates on.
#[derive(Debug, Clone, Default, serde::Serialize, serde::Deserialize, PartialEq)]
pub struct Pack {
    /// Pack points (post-repack; different from `grid.points`).
    pub points: Vec<[f32; 2]>,
    /// Boundary reused from the grid (Azgaar passes `grid.boundary` to the second `calculateVoronoi`).
    pub boundary: Vec<[f32; 2]>,
    /// Cell topology (serialized attributes + `grid_id` mapping).
    pub cells: PackCells,
    /// Voronoi vertices (regenerated by `vor-import` after `reGraph`).
    pub vertices: VoronoiVertices,
    /// Pack features (`pack.features`, slot `[12]`).
    pub features: Vec<Feature>,
}

impl Pack {
    /// Number of pack cells.
    #[inline]
    pub fn points_n(&self) -> usize {
        self.points.len()
    }
}
