[package]
name = "vor-format"
version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
edition = "2021"
description = "Serialización del formato binario .vorn de Voronia (Vorn World File, bincode v1, versionado de formato)."

[lib]
path = "src/lib.rs"

[dependencies]
vor-core = { path = "../vor-core" }
serde.workspace = true
bincode.workspace = true
thiserror.workspace = true

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }
vor-import = { path = "../vor-import" }

[[bench]]
name = "vorn_benchmark"
harness = false
