//! Bit-exact test: `Alea@1.0.1` Rust vs `alea@1.0.1` JS (npm).
//!
//! Loads the first 1000 floats (as `u64` bits serialized as decimal strings to avoid loss
//! when serializing `f64` as JSON) generated by the JS version with seed `861039636` (the
//! one from Brample, the real test `.map`) and verifies that the Rust version produces the
//! same bits. The reference values were generated with `gen_alea_ref_bits.js` running the
//! original source `alea-1.0.1.original.js` with `node`, and are committed in
//! `crates/vor-import/tests/reference/alea_seed_*_first_*_bits.json`.
//!
//! If this test fails, the `grid.points` that vor-import regenerates will not match
//! slot `[6]` of the Azgaar `.map` — see `docs/fase-0-investigacion.md` §6.5,
//! §13.4 consequence 3 (silent bug: attributes in the wrong cells, no error).
//!
//! Note: we serialize as bits and not as rendered decimal strings because `serde_json`
//! parses `0.20791621506214142` to the f64 closest to the string (which may NOT be the same
//! f64 that the JS produced — the string is only the closest printable round-trip, not
//! 1-1 with bits). Serializing bits avoids that ambiguity.

use serde_json::Value;
use std::fs;
use vor_import::prng::Alea;

#[test]
fn alea_rust_matches_js_for_brample_seed() {
    let ref_path = "tests/reference/alea_seed_861039636_first_1000_bits.json";
    let raw =
        fs::read_to_string(ref_path).unwrap_or_else(|e| panic!("could not read {ref_path}: {e}"));
    let arr: Value =
        serde_json::from_str(&raw).unwrap_or_else(|e| panic!("invalid JSON in {ref_path}: {e}"));
    let expected: Vec<u64> = arr
        .as_array()
        .expect("the reference must be a JSON array")
        .iter()
        .map(|v| {
            v.as_str()
                .expect("each element must be a string (bits as decimal string)")
                .parse::<u64>()
                .expect("each string must be a valid decimal u64")
        })
        .collect();
    assert_eq!(
        expected.len(),
        1000,
        "expected exactly 1000 reference values"
    );

    let mut rng = Alea::new("861039636");
    for (i, want_bits) in expected.iter().enumerate() {
        let got = rng.next_f64();
        assert_eq!(
            got.to_bits(),
            *want_bits,
            "alea[{}]: got bits {:#x} ({}) want bits {:#x} ({})",
            i,
            got.to_bits(),
            got,
            want_bits,
            f64::from_bits(*want_bits),
        );
    }
}

/// Additional test with another seed (covers different Mash paths).
#[test]
fn alea_rust_matches_js_for_short_seed() {
    let ref_path = "tests/reference/alea_seed_42_first_100_bits.json";
    let raw = fs::read_to_string(ref_path).expect("fixture for seed '42' must exist");
    let arr: Value = serde_json::from_str(&raw).expect("invalid JSON");
    let expected: Vec<u64> = arr
        .as_array()
        .expect("array expected")
        .iter()
        .map(|v| v.as_str().expect("string").parse::<u64>().expect("u64"))
        .collect();
    let mut rng = Alea::new("42");
    for (i, want_bits) in expected.iter().enumerate() {
        let got = rng.next_f64();
        assert_eq!(
            got.to_bits(),
            *want_bits,
            "seed '42' [{}]: got {:#x} want {:#x} (got {}, want {})",
            i,
            got.to_bits(),
            want_bits,
            got,
            f64::from_bits(*want_bits)
        );
    }
}
