//! Bit-exact test: Delaunay triangulation over `allPoints = points.concat(boundary)`
//! using the crate `delaunator = "1.1"` vs the JS `delaunator@5.1.0` (the one Azgaar uses
//! per `azgaar-fmg/package-lock.json` line 1599: `resolved: delaunator-5.1.0.tgz`).
//!
//! The fixture (`delaunay_grid_2000x2000_c10k_seed_861039636_selfref.json`) was generated by
//! `generate_delaunay_fixture.js` from this dir — it is **self-reference**: the `points` and
//! `boundary` are reproduced from `placePoints` of the current `azgaar-fmg`, and `triangles`/
//! `halfedges` from `delaunator@5.1.0` JS applied over `allPoints`. The Rust test runs
//! `vor_import::geometry::place_points` (already validated bit-exact in `grid_bit_exact.rs`) +
//! `delaunator::triangulate` (Rust crate) and compares both results against the fixture.
//!
//! If the Rust crate does not match bit-by-bit, there is divergence in the triangulation and we
//! must NOT use the crate — the next step would be to port manually from `delaunator-5.1.0.js`.
//! The `azgaar-fmg` consumes `delaunay.triangles` and `delaunay.halfedges` in `voronoi.ts`, so
//! bit-exactness is critical for the `.map` attributes to land on the correct cells (phase-0 §13.4).

use serde_json::Value;
use std::fs;
use vor_import::geometry::delaunay::{from_pairs, EMPTY};
use vor_import::geometry::place_points;

/// Loads the JSON fixture.
fn load_fixture() -> Value {
    let path = "tests/reference/delaunay_grid_2000x2000_c10k_seed_861039636_selfref.json";
    let raw = fs::read_to_string(path).unwrap_or_else(|e| panic!("could not read {path}: {e}"));
    serde_json::from_str(&raw).unwrap_or_else(|e| panic!("invalid JSON: {e}"))
}

/// Parses an array of decimal strings into `Vec<u32>` (values of `triangles`).
fn parse_u32_strings(arr: &Value, field: &str) -> Vec<u32> {
    arr.as_array()
        .unwrap_or_else(|| panic!("`{field}` should be an array"))
        .iter()
        .map(|x| {
            x.as_str()
                .unwrap_or_else(|| panic!("`{field}` entry should be a decimal string"))
                .parse::<u32>()
                .unwrap_or_else(|e| panic!("`{field}` invalid entry: {e}"))
        })
        .collect()
}

/// Parses an array of decimal strings into `Vec<i32>` (values of `halfedges` — -1 = EMPTY).
fn parse_i32_strings(arr: &Value, field: &str) -> Vec<i32> {
    arr.as_array()
        .unwrap_or_else(|| panic!("`{field}` should be an array"))
        .iter()
        .map(|x| {
            x.as_str()
                .unwrap_or_else(|| panic!("`{field}` entry should be a decimal string"))
                .parse::<i32>()
                .unwrap_or_else(|e| panic!("`{field}` invalid entry: {e}"))
        })
        .collect()
}

/// Parses decimal strings of i64 (bits of f64, MSB interpreted as sign by the JS
/// `BigInt64Array`) into `Vec<f64>`. Each string can be negative if the MSB of the f64
/// is set (e.g. y = -20.0 → bits `0xC034000000000000` → BigInt64Array = negative).
fn parse_f64_bits_strings(arr: &Value, field: &str) -> Vec<f64> {
    arr.as_array()
        .unwrap_or_else(|| panic!("`{field}` should be an array"))
        .iter()
        .map(|x| {
            let signed: i64 = x
                .as_str()
                .unwrap_or_else(|| panic!("`{field}` entry should be a decimal string"))
                .parse()
                .unwrap_or_else(|e| panic!("`{field}` invalid bits: {e}"));
            // Reinterpret as u64 without loss (bit transmute).
            f64::from_bits(signed as u64)
        })
        .collect()
}

#[test]
fn delaunator_rust_matches_js_self_reference() {
    let v = load_fixture();

    // Size handshake — if these do not match, the fixture or the Rust changed.
    let n_points: usize = v["nPoints"].as_u64().expect("nPoints u64") as usize;
    let n_boundary: usize = v["nBoundary"].as_u64().expect("nBoundary u64") as usize;
    let n_all_points: usize = v["nAllPoints"].as_u64().expect("nAllPoints u64") as usize;
    let n_triangles: usize = v["nTriangles"].as_u64().expect("nTriangles u64") as usize;
    assert_eq!(
        n_all_points,
        n_points + n_boundary,
        "inconsistent nAllPoints"
    );

    // The fixture `triangles` and `halfedges` (from `delaunator@5.1.0` JS).
    let want_triangles: Vec<u32> = parse_u32_strings(&v["triangles"], "triangles");
    let want_halfedges: Vec<i32> = parse_i32_strings(&v["halfedges"], "halfedges");
    assert_eq!(
        want_triangles.len(),
        n_triangles * 3,
        "triangles.len() inconsistent with nTriangles"
    );
    assert_eq!(
        want_halfedges.len(),
        n_triangles * 3,
        "halfedges.len() inconsistent with nTriangles"
    );

    // (1) `points`+`boundary` handshake: re-produce from the Rust `place_points` and compare
    //     bit-by-bit with the fixture. If this fails, the problem is in `place_points` (not in
    //     `delaunator`) — it should show up first in `grid_bit_exact.rs`.
    let g = place_points(2000.0, 2000.0, 10000, "861039636");
    assert_eq!(g.points.len(), n_points, "place_points.points.len()");
    assert_eq!(g.boundary.len(), n_boundary, "place_points.boundary.len()");
    assert_eq!(
        g.spacing,
        v["spacing"].as_f64().expect("spacing f64"),
        "spacing diverges"
    );

    // Points: 10000 (x,y) → 20000 entries in `points_bits` (flat: x0,y0,x1,y1,...).
    let want_points_flat = parse_f64_bits_strings(&v["points_bits"], "points_bits");
    assert_eq!(
        want_points_flat.len(),
        n_points * 2,
        "inconsistent points_bits.len()"
    );
    for i in 0..n_points {
        let want_x = want_points_flat[2 * i];
        let want_y = want_points_flat[2 * i + 1];
        let got = g.points[i];
        assert_eq!(
            got,
            [want_x, want_y],
            "points[{}] diverges: rust {:?} want {:?} (bits {:#x},{:#x} vs {:#x},{:#x})",
            i,
            got,
            [want_x, want_y],
            got[0].to_bits(),
            got[1].to_bits(),
            want_points_flat[2 * i].to_bits(),
            want_points_flat[2 * i + 1].to_bits(),
        );
    }

    // Boundary: 200 (x,y) → 400 entries in `boundary_bits`.
    let want_boundary_flat = parse_f64_bits_strings(&v["boundary_bits"], "boundary_bits");
    assert_eq!(
        want_boundary_flat.len(),
        n_boundary * 2,
        "inconsistent boundary_bits.len()"
    );
    for i in 0..n_boundary {
        let want_x = want_boundary_flat[2 * i];
        let want_y = want_boundary_flat[2 * i + 1];
        assert_eq!(g.boundary[i], [want_x, want_y], "boundary[{}] diverges", i);
    }

    // (2) Delaunay triangulation with my bit-exact port of `delaunator@5.1.0.js`.
    let mut all_points: Vec<[f64; 2]> = g.points.clone();
    all_points.extend_from_slice(&g.boundary);
    assert_eq!(all_points.len(), n_all_points);

    let result = from_pairs(&all_points);

    // (3) Compare `triangles` bit-by-bit.
    assert_eq!(
        result.triangles.len(),
        n_triangles * 3,
        "triangles.len() diverges: rust {} want {} (n_triangles={})",
        result.triangles.len(),
        n_triangles * 3,
        n_triangles,
    );
    let mut mismatches: Vec<(usize, u32, u32)> = Vec::new();
    for (i, &got) in result.triangles.iter().enumerate() {
        let want = want_triangles[i];
        if got != want {
            mismatches.push((i, got, want));
            if mismatches.len() >= 10 {
                break;
            }
        }
    }
    let mismatches_count = if mismatches.is_empty() {
        "0".to_string()
    } else if mismatches.len() == 10 {
        ">=10".to_string()
    } else {
        mismatches.len().to_string()
    };
    assert!(
        mismatches.is_empty(),
        "triangles diverge in {} entries (first 10: {:?})",
        mismatches_count,
        mismatches,
    );

    // (4) Compare `halfedges` bit-by-bit. My port uses `EMPTY = usize::MAX` for the hull,
    //     equivalent to the `-1` (Int32) of JS. Convert and compare.
    assert_eq!(
        result.halfedges.len(),
        n_triangles * 3,
        "halfedges.len() diverges"
    );
    let mut mismatches: Vec<(usize, i64, i32)> = Vec::new();
    for (i, &got) in result.halfedges.iter().enumerate() {
        let got_i32: i32 = if got == EMPTY { -1 } else { got as i32 };
        let want = want_halfedges[i];
        if got_i32 != want {
            mismatches.push((i, got as i64, want));
            if mismatches.len() >= 10 {
                break;
            }
        }
    }
    let mismatches_count = if mismatches.is_empty() {
        "0".to_string()
    } else if mismatches.len() == 10 {
        ">=10".to_string()
    } else {
        mismatches.len().to_string()
    };
    assert!(
        mismatches.is_empty(),
        "halfedges diverge in {} entries (first 10: {:?})",
        mismatches_count,
        mismatches,
    );

    // (5) Bonus: hull count — Azgaar checks that the boundary (200 points) is the convex hull.
    //     The Rust hull must match 200 (boundary points).
    assert_eq!(
        result.hull.len(),
        n_boundary,
        "hull.len() diverges: rust {} want {} (= n_boundary). The boundary should be the convex hull.",
        result.hull.len(),
        n_boundary,
    );
}
