//! Bit-exact test: the `Voronoi` class of Azgaar (`voronoi.ts`) reproduced in Rust
//! (`vor_import::geometry::voronoi::calculate_voronoi`) over the same input of
//! `placePoints(2000, 2000, 10000, "861039636") + boundary` + `delaunator::from_pairs`.
//!
//! The fixture (`voronoi_grid_2000x2000_c10k_seed_861039636_selfref.json`) was generated by
//! `generate_voronoi_fixture.js` from this dir, replicating the `Voronoi` class of Azgaar
//! in vanilla JS (no TS deps) over the same `Delaunator.from(allPoints)` of the
//! `delaunator@5.1.0`. The Rust test reproduces everything and compares `cells.v/c/b` +
//! `vertices.p/v/c` bit-by-bit against the fixture.
//!
//! Critical: `circumcenter` (`voronoi.ts:142-154`) truncates to integers with `Math.floor`. If the
//! Rust port does not do exactly `f64::floor()`, the `vertices.p[t]` diverge — silent geometry bug
//! that would break the slot→cell mapping (fase-0 §6.3, §13.4).

use serde_json::Value;
use std::fs;
use vor_import::geometry::delaunay::{from_pairs, EMPTY};
use vor_import::geometry::place_points;
use vor_import::geometry::voronoi::calculate_voronoi;

fn load_fixture() -> Value {
    let path = "tests/reference/voronoi_grid_2000x2000_c10k_seed_861039636_selfref.json";
    let raw = fs::read_to_string(path).unwrap_or_else(|e| panic!("could not read {path}: {e}"));
    serde_json::from_str(&raw).unwrap_or_else(|e| panic!("invalid JSON: {e}"))
}

/// Decimal strings of i64 (bits of f64, BigInt64Array) → `Vec<f64>`.
fn parse_f64_bits_strings(arr: &Value, field: &str) -> Vec<f64> {
    arr.as_array()
        .unwrap_or_else(|| panic!("`{field}` should be an array"))
        .iter()
        .map(|x| {
            let signed: i64 = x
                .as_str()
                .unwrap_or_else(|| panic!("`{field}` entry should be a decimal string"))
                .parse()
                .unwrap_or_else(|e| panic!("`{field}` invalid bits: {e}"));
            f64::from_bits(signed as u64)
        })
        .collect()
}

/// Expected: `field` is an array of arrays of u32-strings (cells.v, cells.c).
/// Some entries can be `null` (unvisited cell). Returns `Vec<Option<Vec<u32>>>`.
fn parse_nested_u32_opt(arr: &Value, field: &str) -> Vec<Option<Vec<u32>>> {
    arr.as_array()
        .unwrap_or_else(|| panic!("`{field}` should be an array"))
        .iter()
        .map(|x| {
            if x.is_null() {
                None
            } else {
                Some(
                    x.as_array()
                        .unwrap_or_else(|| panic!("`{field}` entry should be an array or null"))
                        .iter()
                        .map(|s| {
                            s.as_str()
                                .unwrap_or_else(|| {
                                    panic!("`{field}` inner entry should be a string")
                                })
                                .parse::<u32>()
                                .unwrap_or_else(|e| panic!("`{field}` invalid u32: {e}"))
                        })
                        .collect(),
                )
            }
        })
        .collect()
}

/// `field` is an array of decimal strings of u8 (cells.b — "0" or "1"). Some may be null.
/// Returns `Vec<Option<u8>>`.
fn parse_u8_opt_strings(arr: &Value, field: &str) -> Vec<Option<u8>> {
    arr.as_array()
        .unwrap_or_else(|| panic!("`{field}` should be an array"))
        .iter()
        .map(|x| {
            if x.is_null() {
                None
            } else {
                Some(
                    x.as_str()
                        .unwrap_or_else(|| panic!("`{field}` entry should be a string or null"))
                        .parse::<u8>()
                        .unwrap_or_else(|e| panic!("`{field}` invalid u8: {e}")),
                )
            }
        })
        .collect()
}

/// `field` is an array of arrays of 3 i32-strings (vertices.v — -1 = EMPTY).
fn parse_nested_i32(arr: &Value, field: &str) -> Vec<[i64; 3]> {
    arr.as_array()
        .unwrap_or_else(|| panic!("`{field}` should be an array"))
        .iter()
        .map(|x| {
            let arr = x
                .as_array()
                .unwrap_or_else(|| panic!("`{field}` entry should be an array"));
            assert_eq!(arr.len(), 3, "`{field}` entry should have 3 elements");
            let mut out = [0i64; 3];
            for (i, s) in arr.iter().enumerate() {
                out[i] = s
                    .as_str()
                    .unwrap_or_else(|| panic!("`{field}` inner entry should be a string"))
                    .parse::<i64>()
                    .unwrap_or_else(|e| panic!("`{field}` invalid i32: {e}"));
            }
            out
        })
        .collect()
}

/// `field` is an array of arrays of 3 u32-strings (vertices.c).
fn parse_nested_u32(arr: &Value, field: &str) -> Vec<[u32; 3]> {
    arr.as_array()
        .unwrap_or_else(|| panic!("`{field}` should be an array"))
        .iter()
        .map(|x| {
            let arr = x
                .as_array()
                .unwrap_or_else(|| panic!("`{field}` entry should be an array"));
            assert_eq!(arr.len(), 3, "`{field}` entry should have 3 elements");
            let mut out = [0u32; 3];
            for (i, s) in arr.iter().enumerate() {
                out[i] = s
                    .as_str()
                    .unwrap_or_else(|| panic!("`{field}` inner entry should be a string"))
                    .parse::<u32>()
                    .unwrap_or_else(|e| panic!("`{field}` invalid u32: {e}"));
            }
            out
        })
        .collect()
}

#[test]
fn voronoi_rust_matches_js_self_reference() {
    let v = load_fixture();

    // Sanity handshake: spacing, counts, nPoints, nBoundary.
    let spacing = v["spacing"].as_f64().expect("spacing");
    assert!(
        (spacing - 20.0).abs() < 1e-9,
        "spacing matches Brample: {spacing}"
    );
    let n_points = v["nPoints"].as_u64().expect("nPoints") as usize;
    let n_boundary = v["nBoundary"].as_u64().expect("nBoundary") as usize;
    let n_all = v["nAllPoints"].as_u64().expect("nAllPoints") as usize;
    let n_triangles = v["nTriangles"].as_u64().expect("nTriangles") as usize;
    assert_eq!(n_points, 10000, "10000 jittered points");
    assert_eq!(n_boundary, 200, "200 boundary points");
    assert_eq!(n_all, 10200, "allPoints = points + boundary");
    assert_eq!(n_triangles, 20198, "20198 Delaunay triangles");

    // Reproduce `placePoints` from Rust (validated bit-exact in grid_bit_exact.rs).
    let placed = place_points(2000.0, 2000.0, 10000, "861039636");
    assert_eq!(placed.points.len(), n_points);
    assert_eq!(placed.boundary.len(), n_boundary);

    // Concatenate `allPoints = points + boundary` (same as Azgaar in `calculateVoronoi`).
    let mut all_points: Vec<[f64; 2]> = placed.points.clone();
    all_points.extend(placed.boundary.iter().cloned());
    assert_eq!(all_points.len(), n_all);

    // Triangulation (validated bit-exact in delaunay_bit_exact.rs).
    let delaunay = from_pairs(&all_points);
    assert_eq!(delaunay.triangles.len() / 3, n_triangles);
    assert_eq!(delaunay.triangles.len(), 60594);
    assert_eq!(delaunay.halfedges.len(), 60594);
    assert_eq!(delaunay.hull.len(), 200);

    // Compute the Voronoi (Rust port).
    let voronoi = calculate_voronoi(&delaunay, &all_points, n_points as u32);

    // === Validate cells.v ===
    // In the Rust port, unvisited cells are encoded as `Vec::new()` (empty),
    // while the JS leaves them as `undefined` (serialized as `null`). The fixture
    // `cells_v` has `null` for those. In the port, all interior points (id < 10000)
    // MUST be visited (boundary points have id >= 10000 and do not enter `cells_c`).
    // That is why the fixture should have 10000 non-null entries in cells.v.
    // We verify: parse the fixture entries and compare with the Rust.
    let cells_v_json = &v["cells_v"];
    let cells_v_expected = parse_nested_u32_opt(cells_v_json, "cells_v");
    assert_eq!(
        cells_v_expected.len(),
        n_points,
        "cells_v has 10000 entries (one per interior point)"
    );

    // Count of populated cells in the fixture (invariant validation).
    let populated_in_fixture = cells_v_expected.iter().filter(|x| x.is_some()).count();
    assert_eq!(
        populated_in_fixture, n_points,
        "all {n_points} interior points should have a populated cell (fixture)"
    );

    // Compare bit-by-bit: the fixture has `Some(arr)`, the Rust has a populated `Vec<u32>`.
    let mut mismatches_v = 0usize;
    for (p, opt) in cells_v_expected.iter().enumerate() {
        let expected = opt
            .as_ref()
            .unwrap_or_else(|| panic!("cell {p} should be populated"));
        let got = &voronoi.cells.v[p];
        assert!(
            !got.is_empty(),
            "cell {p} is empty in Rust but filled in fixture"
        );
        if got.len() != expected.len() {
            mismatches_v += 1;
            if mismatches_v <= 3 {
                eprintln!(
                    "cells.v[{p}]: lens diverge (Rust={}, JS={})",
                    got.len(),
                    expected.len()
                );
            }
            continue;
        }
        for (i, (g, e)) in got.iter().zip(expected.iter()).enumerate() {
            if g != e {
                mismatches_v += 1;
                if mismatches_v <= 3 {
                    eprintln!("cells.v[{p}][{i}]: Rust={g} JS={e}");
                }
                break;
            }
        }
    }
    assert_eq!(mismatches_v, 0, "{} mismatches in cells.v", mismatches_v);

    // === Validate cells.c ===
    let cells_c_expected = parse_nested_u32_opt(&v["cells_c"], "cells_c");
    assert_eq!(cells_c_expected.len(), n_points);

    let mut mismatches_c = 0usize;
    for (p, opt) in cells_c_expected.iter().enumerate() {
        let expected = opt.as_ref().expect("cell {p} should be populated");
        let got = &voronoi.cells.c[p];
        assert!(
            !got.is_empty(),
            "cells.c[{p}] is empty in Rust but filled in fixture"
        );
        if got.len() != expected.len() {
            mismatches_c += 1;
            if mismatches_c <= 3 {
                eprintln!(
                    "cells.c[{p}]: lens diverge (Rust={}, JS={})",
                    got.len(),
                    expected.len()
                );
            }
            continue;
        }
        for (i, (g, e)) in got.iter().zip(expected.iter()).enumerate() {
            if g != e {
                mismatches_c += 1;
                if mismatches_c <= 3 {
                    eprintln!("cells.c[{p}][{i}]: Rust={g} JS={e}");
                }
                break;
            }
        }
    }
    assert_eq!(mismatches_c, 0, "{} mismatches in cells.c", mismatches_c);

    // === Validate cells.b ===
    let cells_b_json = &v["cells_b"];
    let cells_b_expected = parse_u8_opt_strings(cells_b_json, "cells_b");
    assert_eq!(cells_b_expected.len(), n_points);

    let mut mismatches_b = 0usize;
    for (p, opt) in cells_b_expected.iter().enumerate() {
        let expected = opt.unwrap_or_else(|| panic!("cells.b[{p}] should be set"));
        let got = voronoi.cells.b[p];
        if got != expected {
            mismatches_b += 1;
            if mismatches_b <= 5 {
                eprintln!("cells.b[{p}]: Rust={got} JS={expected}");
            }
        }
    }
    assert_eq!(mismatches_b, 0, "{} mismatches in cells.b", mismatches_b);

    // === Validate vertices.p (bit-exact coords with Math.floor) ===
    let vertices_p_bits = &v["vertices_p_bits"];
    let vertices_p_flat = parse_f64_bits_strings(vertices_p_bits, "vertices_p_bits");
    assert_eq!(
        vertices_p_flat.len(),
        n_triangles * 2,
        "vertices.p_bits should be nTriangles*2 f64 entries"
    );

    let mut mismatches_p = 0usize;
    for t in 0..n_triangles {
        let expected_x = vertices_p_flat[2 * t];
        let expected_y = vertices_p_flat[2 * t + 1];
        let got = &voronoi.vertices.p[t];
        if (got[0] - expected_x).abs() > 0.0 || (got[1] - expected_y).abs() > 0.0 {
            mismatches_p += 1;
            if mismatches_p <= 3 {
                eprintln!(
                    "vertices.p[{t}]: Rust={:?} JS=[{expected_x}, {expected_y}]",
                    got
                );
            }
        }
    }
    assert_eq!(mismatches_p, 0, "{} mismatches in vertices.p", mismatches_p);

    // === Validate vertices.v (3 triangle ids per vertex, -1 = EMPTY) ===
    let vertices_v_expected = parse_nested_i32(&v["vertices_v"], "vertices_v");
    assert_eq!(vertices_v_expected.len(), n_triangles);

    let mut mismatches_vv = 0usize;
    for (t, expected) in vertices_v_expected.iter().enumerate() {
        let got = &voronoi.vertices.v[t];
        for (i, (g, e)) in got.iter().zip(expected.iter()).enumerate() {
            // JS: -1 = EMPTY (Math.floor(-1/3) = -1 — JS truncates toward zero, not floor; but
            // floor(-1/3) = -1 too).
            // Rust: we store `EMPTY = usize::MAX` (= 4294967295 u32) which we serialize
            // as `usize`. To compare with the JS, we map EMPTY → -1.
            let g_i64 = if *g == EMPTY { -1i64 } else { *g as i64 };
            if g_i64 != *e {
                mismatches_vv += 1;
                if mismatches_vv <= 3 {
                    eprintln!("vertices.v[{t}][{i}]: Rust={g_i64} JS={e} (raw Rust usize={g})");
                }
                break;
            }
        }
    }
    assert_eq!(
        mismatches_vv, 0,
        "{} mismatches in vertices.v",
        mismatches_vv
    );

    // === Validate vertices.c (3 u32 cell ids per vertex) ===
    let vertices_c_expected = parse_nested_u32(&v["vertices_c"], "vertices_c");
    assert_eq!(vertices_c_expected.len(), n_triangles);

    let mut mismatches_vc = 0usize;
    for (t, expected) in vertices_c_expected.iter().enumerate() {
        let got = &voronoi.vertices.c[t];
        if got != expected {
            mismatches_vc += 1;
            if mismatches_vc <= 3 {
                eprintln!("vertices.c[{t}]: Rust={got:?} JS={expected:?}");
            }
        }
    }
    assert_eq!(
        mismatches_vc, 0,
        "{} mismatches in vertices.c",
        mismatches_vc
    );

    // Test passes. Human-readable success summary on stderr.
    eprintln!(
        "[voronoi bit-exact] OK: {} cells, {} triangles — 0 mismatches in cells.v/c/b and vertices.p/v/c",
        n_points, n_triangles
    );
}
