[package]
name = "vor-app"
version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
edition = "2021"
description = "Binario final de Voronia: winit + egui + wgpu + orquestación de crates."

[lib]
path = "src/lib.rs"

[[bin]]
name = "vor-app"
path = "src/main.rs"

[dependencies]
vor-core = { path = "../vor-core" }
vor-format = { path = "../vor-format" }
vor-import = { path = "../vor-import" }
vor-render = { path = "../vor-render" }
vor-edit = { path = "../vor-edit" }
vor-sim = { path = "../vor-sim" }
wgpu.workspace = true
winit.workspace = true
egui.workspace = true
egui-wgpu.workspace = true
egui-winit.workspace = true
glam.workspace = true
pollster.workspace = true
bytemuck.workspace = true
thiserror.workspace = true
anyhow.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
image.workspace = true

[dev-dependencies]
serde_json.workspace = true
