//! Heightmap layer: tessellates the `Grid` cells with `lyon` and builds
//! vertex/index buffers for wgpu.
//!
//! Each cell `p` of the grid is the closed polygon formed by the circumcenters
//! of the adjacent Delaunay triangles (the IDs in `grid.vertices.cell_rings[p]`
//! -> the position is in `grid.vertices.positions[t]`). In Azgaar this ordering
//! comes from `edgesAroundPoint` (CCW). Lyon walks the points in the given order.
//!
//! Height-based color: uses an Azgaar-style ramp ("Heightmap show"):
//! height < 20 -> blue (sea, darker the lower); 20 = coast; > 20 -> green
//! to brown/white by height. It is only a visual ramp for the Phase 2 viewer;
//! it does not replace the biome system (Phase 3).

use bytemuck::{Pod, Zeroable};
use lyon::geom::point;
use lyon::path::Path;
use lyon::tessellation::{
    BuffersBuilder, FillOptions, FillTessellator, FillVertexConstructor, VertexBuffers,
};
use vor_core::Grid;

use crate::mesh::laplacian_smooth_vertices;

/// A terrain buffer vertex: position (world pixels) + color (linear RGBA).
#[repr(C)]
#[derive(Clone, Copy, Pod, Zeroable, Debug, Default)]
pub struct HeightmapVertex {
    pub pos: [f32; 2],
    /// Linear RGBA color (the shader does not apply gamma).
    pub color: [f32; 4],
}

/// Tessellated mesh ready to be uploaded to the GPU.
#[derive(Clone, Debug)]
pub struct HeightmapMesh {
    pub vertices: Vec<HeightmapVertex>,
    pub indices: Vec<u32>,
    /// World bounding box (min/max in pixels) for the initial framing.
    pub bounds_min: [f32; 2],
    pub bounds_max: [f32; 2],
}

/// Lyon vertex constructor: returns a `HeightmapVertex` for each vertex
/// generated by the tessellator (with the fixed cell color).
pub(crate) struct ColorCtor(pub(crate) [f32; 4]);

impl FillVertexConstructor<HeightmapVertex> for ColorCtor {
    fn new_vertex(&mut self, vertex: lyon::tessellation::FillVertex<'_>) -> HeightmapVertex {
        let p = vertex.position();
        HeightmapVertex {
            pos: [p.x, p.y],
            color: self.0,
        }
    }
}

/// Builds the `HeightmapMesh` from the `Grid`.
///
/// - Iterates over the `grid.points.len()` real cells (no boundary).
/// - For each one, builds the closed polygon path with the Voronoi vertices
///   listed in `grid.vertices.cell_rings[p]`, tessellates it with `lyon`, and
///   appends it to the global mesh, offsetting indices.
/// - Computes the final bounding box.
///
/// Cells with an empty `cell_rings[p]` (malformed boundary) are skipped.
pub fn build_mesh(grid: &Grid) -> HeightmapMesh {
    // Laplacian smoothing of the Voronoi mesh: rounds the cells without
    // breaking watertightness (shared vertices -> no gaps between adjacent cells).
    let smooth_vertices = laplacian_smooth_vertices(&grid.vertices, 0.2, 2);

    let n_cells = grid.points_n();
    let mut vertices: Vec<HeightmapVertex> = Vec::with_capacity(n_cells * 6);
    let mut indices: Vec<u32> = Vec::with_capacity(n_cells * 9);
    let mut bounds_min = [f32::INFINITY, f32::INFINITY];
    let mut bounds_max = [f32::NEG_INFINITY, f32::NEG_INFINITY];

    let mut tess = FillTessellator::new();

    for p in 0..n_cells {
        let ann = match grid.vertices.cell_rings.get(p) {
            Some(v) if !v.is_empty() => v,
            _ => continue,
        };
        let h = grid.cells.height.get(p).copied().unwrap_or(0);
        let color = height_color(h);

        // Path of the closed polygon using smoothed positions.
        let first_t = ann[0] as usize;
        let first_pos = smooth_vertices
            .positions
            .get(first_t)
            .copied()
            .unwrap_or([0.0, 0.0]);
        let mut builder = Path::builder();
        builder.begin(point(first_pos[0], first_pos[1]));
        for &t in ann.iter().skip(1) {
            let ti = t as usize;
            let pos = smooth_vertices
                .positions
                .get(ti)
                .copied()
                .unwrap_or([0.0, 0.0]);
            builder.line_to(point(pos[0], pos[1]));
        }
        builder.end(true);
        let path = builder.build();

        let mut mesh: VertexBuffers<HeightmapVertex, u32> = VertexBuffers::new();
        let mut buffer_builder = BuffersBuilder::new(&mut mesh, ColorCtor(color));
        let opts = FillOptions::default().with_fill_rule(lyon::tessellation::FillRule::EvenOdd);

        if tess
            .tessellate_path(&path, &opts, &mut buffer_builder)
            .is_err()
        {
            continue; // Skip degenerate cells.
        }

        let base = vertices.len() as u32;
        vertices.extend_from_slice(&mesh.vertices);
        indices.extend(mesh.indices.iter().map(|i| i + base));

        for v in &mesh.vertices {
            bounds_min[0] = bounds_min[0].min(v.pos[0]);
            bounds_min[1] = bounds_min[1].min(v.pos[1]);
            bounds_max[0] = bounds_max[0].max(v.pos[0]);
            bounds_max[1] = bounds_max[1].max(v.pos[1]);
        }
    }

    if !bounds_min[0].is_finite() {
        bounds_min = [0.0, 0.0];
        bounds_max = [grid.width, grid.height];
    }

    HeightmapMesh {
        vertices,
        indices,
        bounds_min,
        bounds_max,
    }
}

/// The "Spectral" color scheme, exactly as Azgaar's default heightmap scheme
/// `"bright"` (d3 `scaleSequential(interpolateSpectral)`). Stops are the 11
/// sRGB colors of d3's Spectral ramp, in sRGB bytes; interpolation follows
/// d3 `interpolateRgbBasis` (Catmull-Rom/B-spline over each channel).
static SPECTRAL_STOPS: [[u8; 3]; 11] = [
    [0x9e, 0x01, 0x42], // #9e0142
    [0xd3, 0x3e, 0x4f], // #d53e4f
    [0xf4, 0x6d, 0x43], // #f46d43
    [0xfd, 0xae, 0x61], // #fdae61
    [0xfe, 0xe0, 0x8b], // #fee08b
    [0xff, 0xff, 0xbf], // #ffffbf
    [0xe6, 0xf5, 0x98], // #e6f598
    [0xab, 0xdd, 0xa4], // #abdda4
    [0x66, 0xc2, 0xa5], // #66c2a5
    [0x32, 0x88, 0xbd], // #3288bd
    [0x5e, 0x4f, 0xa2], // #5e4fa2
];

/// A single channel `[u8;3]` stop parsed to the channel value.
#[inline]
fn chan(c: u8) -> f32 {
    c as f32 / 255.0
}

/// d3 `interpolateRgbBasis(values)` — Catmull-Rom/B-spline interpolation over
/// each channel independently, matching `getColorScheme("bright")`.
fn spectral(t: f32) -> [f32; 3] {
    let n = SPECTRAL_STOPS.len();
    if t >= 1.0 {
        return [
            chan(SPECTRAL_STOPS[n - 1][0]),
            chan(SPECTRAL_STOPS[n - 1][1]),
            chan(SPECTRAL_STOPS[n - 1][2]),
        ];
    }
    if t <= 0.0 {
        return [
            chan(SPECTRAL_STOPS[0][0]),
            chan(SPECTRAL_STOPS[0][1]),
            chan(SPECTRAL_STOPS[0][2]),
        ];
    }
    let full: f32 = (n - 1) as f32;
    let tt = t * full;
    let i = tt.floor().min((n - 2) as f32) as usize;
    let t = (tt - i as f32).clamp(0.0, 1.0).min(1.0 - 1e-6);
    let t2 = t * t;
    let t3 = t2 * t;
    let (w0, w1, w2, w3) = (
        (1.0 - 3.0 * t + 3.0 * t2 - t3) / 6.0,
        (4.0 - 6.0 * t2 + 3.0 * t3) / 6.0,
        (1.0 + 3.0 * t + 3.0 * t2 - 3.0 * t3) / 6.0,
        t3 / 6.0,
    );
    // Neighbours clamped to the first/last stop at the boundaries.
    let v0 = if i == 0 {
        SPECTRAL_STOPS[0]
    } else {
        SPECTRAL_STOPS[i - 1]
    };
    let v1 = SPECTRAL_STOPS[i];
    let v2 = SPECTRAL_STOPS[n.min(i + 2) - 1];
    let v3 = SPECTRAL_STOPS[n.min(i + 3) - 1];
    let mix = |a: [u8; 3], b: [u8; 3]| {
        let f = |c0: u8, c1: u8, c2: u8, c3: u8| {
            w0 * chan(c0) + w1 * chan(c1) + w2 * chan(c2) + w3 * chan(c3)
        };
        [
            f(a[0], b[0], v2[0], v3[0]),
            f(a[1], b[1], v2[1], v3[1]),
            f(a[2], b[2], v2[2], v3[2]),
        ]
    };
    mix(v0, v1)
}

/// Azgaar heightmap color for a height value.
///
/// Mirrors FMG `getColor(value, scheme)`:
/// ```js
/// scheme(1 - (value < 20 ? value - 5 : value) / 100)
/// ```
/// The resulting sRGB ramp is converted to **linear** RGBA (the wgpu shader
/// does not apply gamma) via the standard sRGB OETF.
pub fn height_color(h: u8) -> [f32; 4] {
    let value = h.min(100) as f32;
    let offset = if value < 20.0 { value - 5.0 } else { value };
    let t = 1.0 - offset / 100.0;
    let srgb = spectral(t.clamp(0.0, 1.0));
    [
        srgb_to_linear(srgb[0]),
        srgb_to_linear(srgb[1]),
        srgb_to_linear(srgb[2]),
        1.0,
    ]
}

#[inline]
fn srgb_to_linear(c: f32) -> f32 {
    if c <= 0.04045 {
        c / 12.92
    } else {
        ((c + 0.055) / 1.055).powf(2.4)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn height_color_sea_is_dark_purple() {
        // h=0 -> offset -5 -> t=1.05 -> clamped to 1.0 -> last Spectral stop #5e4fa2 (deep blue-violet).
        let c = height_color(0);
        assert!(
            c[2] > c[0] && c[2] > c[1],
            "deep sea should be bluish, got {c:?}"
        );
        assert_eq!(c[3], 1.0);
    }

    #[test]
    fn height_color_summit_is_dark_red() {
        // h=100 -> t=0 -> first Spectral stop #9e0142 (deep red).
        let c = height_color(100);
        assert!(
            c[0] > c[1] && c[0] > c[2],
            "summit should be reddish, got {c:?}"
        );
    }

    #[test]
    fn height_color_midland_is_light() {
        // h≈40 -> t≈0.6 -> near the pale central stop of Spectral (#ffffbf/#e6f598):
        // bright red + green, low blue.
        let c = height_color(40);
        assert!(
            c[0] > 0.6 && c[1] > 0.6 && c[2] < c[1],
            "midland should be light (bright R/G, low B), got {c:?}"
        );
    }

    #[test]
    fn height_color_clamp_above_100() {
        let _ = height_color(255);
    }
}
