//! Heightmap layer: tessellates the `Grid` cells with `lyon` and builds
//! vertex/index buffers for wgpu.
//!
//! Each cell `p` of the grid is the closed polygon formed by the circumcenters
//! of the adjacent Delaunay triangles (the IDs in `grid.vertices.cell_rings[p]`
//! -> the position is in `grid.vertices.positions[t]`). In Azgaar this ordering
//! comes from `edgesAroundPoint` (CCW). Lyon walks the points in the given order.
//!
//! Height-based color: uses an Azgaar-style ramp ("Heightmap show"):
//! height < 20 -> blue (sea, darker the lower); 20 = coast; > 20 -> green
//! to brown/white by height. It is only a visual ramp for the Phase 2 viewer;
//! it does not replace the biome system (Phase 3).

use bytemuck::{Pod, Zeroable};
use lyon::geom::point;
use lyon::path::Path;
use lyon::tessellation::{
    BuffersBuilder, FillOptions, FillTessellator, FillVertexConstructor, VertexBuffers,
};
use vor_core::Grid;

use crate::mesh::laplacian_smooth_vertices;

/// A terrain buffer vertex: position (world pixels) + color (linear RGBA).
#[repr(C)]
#[derive(Clone, Copy, Pod, Zeroable, Debug, Default)]
pub struct HeightmapVertex {
    pub pos: [f32; 2],
    /// Linear RGBA color (the shader does not apply gamma).
    pub color: [f32; 4],
}

/// Tessellated mesh ready to be uploaded to the GPU.
#[derive(Clone, Debug)]
pub struct HeightmapMesh {
    pub vertices: Vec<HeightmapVertex>,
    pub indices: Vec<u32>,
    /// World bounding box (min/max in pixels) for the initial framing.
    pub bounds_min: [f32; 2],
    pub bounds_max: [f32; 2],
}

/// Lyon vertex constructor: returns a `HeightmapVertex` for each vertex
/// generated by the tessellator (with the fixed cell color).
pub(crate) struct ColorCtor(pub(crate) [f32; 4]);

impl FillVertexConstructor<HeightmapVertex> for ColorCtor {
    fn new_vertex(&mut self, vertex: lyon::tessellation::FillVertex<'_>) -> HeightmapVertex {
        let p = vertex.position();
        HeightmapVertex {
            pos: [p.x, p.y],
            color: self.0,
        }
    }
}

/// Builds the `HeightmapMesh` from the `Grid`.
///
/// - Iterates over the `grid.points.len()` real cells (no boundary).
/// - For each one, builds the closed polygon path with the Voronoi vertices
///   listed in `grid.vertices.cell_rings[p]`, tessellates it with `lyon`, and
///   appends it to the global mesh, offsetting indices.
/// - Computes the final bounding box.
///
/// Cells with an empty `cell_rings[p]` (malformed boundary) are skipped.
pub fn build_mesh(grid: &Grid) -> HeightmapMesh {
    // Laplacian smoothing of the Voronoi mesh: rounds the cells without
    // breaking watertightness (shared vertices -> no gaps between adjacent cells).
    let smooth_vertices = laplacian_smooth_vertices(&grid.vertices, 0.2, 2);

    let n_cells = grid.points_n();
    let mut vertices: Vec<HeightmapVertex> = Vec::with_capacity(n_cells * 6);
    let mut indices: Vec<u32> = Vec::with_capacity(n_cells * 9);
    let mut bounds_min = [f32::INFINITY, f32::INFINITY];
    let mut bounds_max = [f32::NEG_INFINITY, f32::NEG_INFINITY];

    let mut tess = FillTessellator::new();

    for p in 0..n_cells {
        let ann = match grid.vertices.cell_rings.get(p) {
            Some(v) if !v.is_empty() => v,
            _ => continue,
        };
        let h = grid.cells.height.get(p).copied().unwrap_or(0);
        let color = height_color(h);

        // Path of the closed polygon using smoothed positions.
        let first_t = ann[0] as usize;
        let first_pos = smooth_vertices
            .positions
            .get(first_t)
            .copied()
            .unwrap_or([0.0, 0.0]);
        let mut builder = Path::builder();
        builder.begin(point(first_pos[0], first_pos[1]));
        for &t in ann.iter().skip(1) {
            let ti = t as usize;
            let pos = smooth_vertices
                .positions
                .get(ti)
                .copied()
                .unwrap_or([0.0, 0.0]);
            builder.line_to(point(pos[0], pos[1]));
        }
        builder.end(true);
        let path = builder.build();

        let mut mesh: VertexBuffers<HeightmapVertex, u32> = VertexBuffers::new();
        let mut buffer_builder = BuffersBuilder::new(&mut mesh, ColorCtor(color));
        let opts = FillOptions::default().with_fill_rule(lyon::tessellation::FillRule::EvenOdd);

        if tess
            .tessellate_path(&path, &opts, &mut buffer_builder)
            .is_err()
        {
            continue; // Skip degenerate cells.
        }

        let base = vertices.len() as u32;
        vertices.extend_from_slice(&mesh.vertices);
        indices.extend(mesh.indices.iter().map(|i| i + base));

        for v in &mesh.vertices {
            bounds_min[0] = bounds_min[0].min(v.pos[0]);
            bounds_min[1] = bounds_min[1].min(v.pos[1]);
            bounds_max[0] = bounds_max[0].max(v.pos[0]);
            bounds_max[1] = bounds_max[1].max(v.pos[1]);
        }
    }

    if !bounds_min[0].is_finite() {
        bounds_min = [0.0, 0.0];
        bounds_max = [grid.width, grid.height];
    }

    HeightmapMesh {
        vertices,
        indices,
        bounds_min,
        bounds_max,
    }
}

/// The "Spectral" color scheme, exactly as Azgaar's default heightmap scheme
/// `"bright"` (d3 `scaleSequential(interpolateSpectral)`). Stops are the 11
/// sRGB colors of d3's Spectral ramp, in sRGB bytes; interpolation follows
/// d3 `interpolateRgbBasis` (Catmull-Rom/B-spline over each channel).
static SPECTRAL_STOPS: [[u8; 3]; 11] = [
    [0x9e, 0x01, 0x42], // #9e0142
    [0xd3, 0x3e, 0x4f], // #d53e4f
    [0xf4, 0x6d, 0x43], // #f46d43
    [0xfd, 0xae, 0x61], // #fdae61
    [0xfe, 0xe0, 0x8b], // #fee08b
    [0xff, 0xff, 0xbf], // #ffffbf
    [0xe6, 0xf5, 0x98], // #e6f598
    [0xab, 0xdd, 0xa4], // #abdda4
    [0x66, 0xc2, 0xa5], // #66c2a5
    [0x32, 0x88, 0xbd], // #3288bd
    [0x5e, 0x4f, 0xa2], // #5e4fa2
];

/// A single channel `[u8;3]` stop parsed to the channel value.
#[inline]
fn chan(c: u8) -> f32 {
    c as f32 / 255.0
}

/// d3 `interpolateRgbBasis(values)` — Catmull-Rom/B-spline interpolation over
/// each channel independently.
fn rgb_basis(stops: &[[u8; 3]], t: f32) -> [f32; 3] {
    let n = stops.len();
    if t >= 1.0 {
        return [
            chan(stops[n - 1][0]),
            chan(stops[n - 1][1]),
            chan(stops[n - 1][2]),
        ];
    }
    if t <= 0.0 {
        return [chan(stops[0][0]), chan(stops[0][1]), chan(stops[0][2])];
    }
    let full: f32 = (n - 1) as f32;
    let tt = t * full;
    let i = tt.floor().min((n - 2) as f32) as usize;
    let t = (tt - i as f32).clamp(0.0, 1.0).min(1.0 - 1e-6);
    let t2 = t * t;
    let t3 = t2 * t;
    let (w0, w1, w2, w3) = (
        (1.0 - 3.0 * t + 3.0 * t2 - t3) / 6.0,
        (4.0 - 6.0 * t2 + 3.0 * t3) / 6.0,
        (1.0 + 3.0 * t + 3.0 * t2 - 3.0 * t3) / 6.0,
        t3 / 6.0,
    );
    // Neighbours clamped to the first/last stop at the boundaries.
    let v0 = if i == 0 { stops[0] } else { stops[i - 1] };
    let v1 = stops[i];
    let v2 = stops[n.min(i + 2) - 1];
    let v3 = stops[n.min(i + 3) - 1];
    let mix = |a: [u8; 3], b: [u8; 3]| {
        let f = |c0: u8, c1: u8, c2: u8, c3: u8| {
            w0 * chan(c0) + w1 * chan(c1) + w2 * chan(c2) + w3 * chan(c3)
        };
        [
            f(a[0], b[0], v2[0], v3[0]),
            f(a[1], b[1], v2[1], v3[1]),
            f(a[2], b[2], v2[2], v3[2]),
        ]
    };
    mix(v0, v1)
}

fn spectral(t: f32) -> [f32; 3] {
    rgb_basis(&SPECTRAL_STOPS, t)
}

/// FMG heightmap color schemes (`style.js heightmapColorSchemes`).
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum HeightmapScheme {
    /// Default. `scaleSequential(interpolateSpectral)`.
    Bright,
    /// `scaleSequential(interpolateRdYlGn)` (ColorBrewer 11 stops).
    Light,
    /// `interpolateRgbBasis(["white","#EEEECC","tan","green","teal"])`.
    Natural,
    /// `interpolateGreens` (ColorBrewer 9 stops).
    Green,
    /// `interpolateRgbBasis(["#ffffff","#cea48d","#d5b085","#0c2c19","#151320"])`.
    Olive,
    /// `interpolateRgbBasis(["#BBBBDD","#2A3440","#17343B","#0A1E24"])`.
    Livid,
    /// `interpolateGreys` (ColorBrewer 9 stops).
    Monochrome,
}

impl HeightmapScheme {
    pub const ALL: [HeightmapScheme; 7] = [
        HeightmapScheme::Bright,
        HeightmapScheme::Light,
        HeightmapScheme::Natural,
        HeightmapScheme::Green,
        HeightmapScheme::Olive,
        HeightmapScheme::Livid,
        HeightmapScheme::Monochrome,
    ];

    pub fn name(&self) -> &'static str {
        match self {
            HeightmapScheme::Bright => "bright",
            HeightmapScheme::Light => "light",
            HeightmapScheme::Natural => "natural",
            HeightmapScheme::Green => "green",
            HeightmapScheme::Olive => "olive",
            HeightmapScheme::Livid => "livid",
            HeightmapScheme::Monochrome => "monochrome",
        }
    }

    fn hex_stops(&self) -> Vec<[u8; 3]> {
        let parse = |s: &str| {
            let h = s.trim_start_matches('#');
            [
                u8::from_str_radix(&h[0..2], 16).unwrap_or(0),
                u8::from_str_radix(&h[2..4], 16).unwrap_or(0),
                u8::from_str_radix(&h[4..6], 16).unwrap_or(0),
            ]
        };
        match self {
            // interpolateSpectral == rgbBasis(Spectral 11).
            HeightmapScheme::Bright => SPECTRAL_STOPS.to_vec(),
            // ColorBrewer RdYlGn (11).
            HeightmapScheme::Light => [
                "#a50026", "#d73027", "#f46d43", "#fdae61", "#fee08b", "#ffffbf", "#d9ef8b",
                "#a6d96a", "#66bd63", "#1a9850", "#006837",
            ]
            .iter()
            .map(|&s| parse(s))
            .collect(),
            HeightmapScheme::Natural => ["white", "#EEEECC", "tan", "green", "teal"]
                .iter()
                .map(|&s| named_color(s))
                .collect(),
            // ColorBrewer Greens (9).
            HeightmapScheme::Green => [
                "#f7fcf5", "#e5f5e0", "#c7e9c0", "#a1d99b", "#74c476", "#41ab5d", "#238b45",
                "#006d2c", "#00441b",
            ]
            .iter()
            .map(|&s| parse(s))
            .collect(),
            HeightmapScheme::Olive => ["#ffffff", "#cea48d", "#d5b085", "#0c2c19", "#151320"]
                .iter()
                .map(|&s| parse(s))
                .collect(),
            HeightmapScheme::Livid => ["#BBBBDD", "#2A3440", "#17343B", "#0A1E24"]
                .iter()
                .map(|&s| parse(s))
                .collect(),
            // ColorBrewer Greys (9).
            HeightmapScheme::Monochrome => [
                "#ffffff", "#f0f0f0", "#d9d9d9", "#bdbdbd", "#969696", "#737373", "#525252",
                "#252525", "#000000",
            ]
            .iter()
            .map(|&s| parse(s))
            .collect(),
        }
    }

    /// `scheme(t)` for `t ∈ [0,1]` — linear RGBA output.
    pub fn at(&self, t: f32) -> [f32; 4] {
        let srgb = match self {
            HeightmapScheme::Bright => spectral(t.clamp(0.0, 1.0)),
            _ => rgb_basis(&self.hex_stops(), t.clamp(0.0, 1.0)),
        };
        [
            srgb_to_linear(srgb[0]),
            srgb_to_linear(srgb[1]),
            srgb_to_linear(srgb[2]),
            1.0,
        ]
    }
}

/// Minimal CSS named-color table for the `natural` scheme stops.
fn named_color(name: &str) -> [u8; 3] {
    match name {
        "white" => [0xff, 0xff, 0xff],
        "tan" => [0xd2, 0xb4, 0x8c],
        "green" => [0x00, 0x80, 0x00],
        "teal" => [0x00, 0x80, 0x80],
        _ => [0xff, 0xff, 0xff],
    }
}

/// Azgaar heightmap color for a height value.
///
/// Mirrors FMG `getColor(value, scheme)`:
/// ```js
/// scheme(1 - (value < 20 ? value - 5 : value) / 100)
/// ```
/// The resulting sRGB ramp is converted to **linear** RGBA (the wgpu shader
/// does not apply gamma) via the standard sRGB OETF.
pub fn height_color(h: u8) -> [f32; 4] {
    height_color_scheme(HeightmapScheme::Bright, h)
}

/// FMG `getColor(value, scheme)` for any of the 7 schemes.
pub fn height_color_scheme(scheme: HeightmapScheme, h: u8) -> [f32; 4] {
    let value = h.min(100) as f32;
    let offset = if value < 20.0 { value - 5.0 } else { value };
    let t = 1.0 - offset / 100.0;
    scheme.at(t.clamp(0.0, 1.0))
}

/// d3 `color.darker(k)`: multiply each channel by `0.7^k` (in sRGB space).
pub fn darken(c: [f32; 4], k: f32) -> [f32; 4] {
    let f = 0.7_f32.powf(k);
    // c is linear here; convert to sRGB, scale, convert back (d3 works in sRGB).
    let inv = |x: f32| {
        let srgb = if x <= 0.003_130_8 {
            x * 12.92
        } else {
            1.055 * x.powf(1.0 / 2.4) - 0.055
        };
        (srgb * f).clamp(0.0, 1.0)
    };
    [
        srgb_to_linear(inv(c[0])),
        srgb_to_linear(inv(c[1])),
        srgb_to_linear(inv(c[2])),
        c[3],
    ]
}

#[inline]
fn srgb_to_linear(c: f32) -> f32 {
    if c <= 0.04045 {
        c / 12.92
    } else {
        ((c + 0.055) / 1.055).powf(2.4)
    }
}

/// Spectral color in **linear** RGBA for a normalized value `t ∈ [0,1]`
/// (`0` → first stop, `1` → last stop). Same ramp as `height_color` but exposed
/// for other layers (temperature, precipitation) that use `scheme(...)`.
pub fn spectral_linear(t: f32) -> [f32; 4] {
    let srgb = spectral(t.clamp(0.0, 1.0));
    [
        srgb_to_linear(srgb[0]),
        srgb_to_linear(srgb[1]),
        srgb_to_linear(srgb[2]),
        1.0,
    ]
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn height_color_sea_is_dark_purple() {
        // h=0 -> offset -5 -> t=1.05 -> clamped to 1.0 -> last Spectral stop #5e4fa2 (deep blue-violet).
        let c = height_color(0);
        assert!(
            c[2] > c[0] && c[2] > c[1],
            "deep sea should be bluish, got {c:?}"
        );
        assert_eq!(c[3], 1.0);
    }

    #[test]
    fn height_color_summit_is_dark_red() {
        // h=100 -> t=0 -> first Spectral stop #9e0142 (deep red).
        let c = height_color(100);
        assert!(
            c[0] > c[1] && c[0] > c[2],
            "summit should be reddish, got {c:?}"
        );
    }

    #[test]
    fn height_color_midland_is_light() {
        // h≈40 -> t≈0.6 -> near the pale central stop of Spectral (#ffffbf/#e6f598):
        // bright red + green, low blue.
        let c = height_color(40);
        assert!(
            c[0] > 0.6 && c[1] > 0.6 && c[2] < c[1],
            "midland should be light (bright R/G, low B), got {c:?}"
        );
    }

    #[test]
    fn height_color_clamp_above_100() {
        let _ = height_color(255);
    }

    #[test]
    fn all_schemes_produce_valid_colors() {
        for scheme in HeightmapScheme::ALL {
            let low = height_color_scheme(scheme, 20);
            let high = height_color_scheme(scheme, 100);
            assert_eq!(low[3], 1.0);
            assert_eq!(high[3], 1.0);
            assert!(
                low.iter().all(|v| v.is_finite()) && high.iter().all(|v| v.is_finite()),
                "{:?} produced non-finite channels",
                scheme
            );
        }
        // Monochrome: getColor maps high h to t≈0 → first Greys stop (white).
        let top = height_color_scheme(HeightmapScheme::Monochrome, 100);
        assert!(top[0] > 0.98 && (top[0] - top[2]).abs() < 1e-6);
        // Low land (h=20 → t=0.8) lands deep in the dark end of Greys.
        let low = height_color_scheme(HeightmapScheme::Monochrome, 20);
        assert!(low[0] < 0.35);
    }

    #[test]
    fn darken_matches_d3_formula() {
        // d3 darker(1) multiplies sRGB by 0.7; white stays neutral gray.
        let w = [
            srgb_to_linear(1.0),
            srgb_to_linear(1.0),
            srgb_to_linear(1.0),
            1.0,
        ];
        let d = darken(w, 1.0);
        let expected = srgb_to_linear(0.7);
        assert!((d[0] - expected).abs() < 1e-6);
        assert_eq!(d[3], 1.0);
        // darker(0) is a no-op.
        let same = darken(w, 0.0);
        assert!((same[0] - w[0]).abs() < 1e-6);
    }
}
