//! Routes layer (FMG `#routes` with subgroups `#roads`/`#trails`/`#searoutes`).
//!
//! Each route is drawn as a Catmull-Rom curve (`Routes.getPath`,
//! `routes-generator.ts:860-873`): roads/trails `curveCatmullRom.alpha(0.1)`,
//! searoutes `alpha(0.5)`, sampled and stroked with the subgroup style from
//! `default.json`:
//!
//! | group     | stroke    | width | dash       | linecap | opacity |
//! |-----------|-----------|-------|------------|---------|---------|
//! | roads     | `#d06324` | 0.7   | `2`        | butt    | 0.9     |
//! | trails    | `#d06324` | 0.25  | `.8 1.6`   | butt    | 0.9     |
//! | searoutes | `#ffffff` | 0.35  | `1 2`      | round   | 0.9     |
//!
//! Dashes are generated by walking the sampled polyline and emitting `on`
//! runs (SVG stroke-dasharray has no lyon equivalent). Routes with fewer
//! than 2 points are skipped, like FMG.

use lyon::tessellation::{
    BuffersBuilder, LineCap, LineJoin, StrokeOptions, StrokeTessellator, StrokeVertexConstructor,
    VertexBuffers,
};
use vor_core::entities::route::{Route, RouteGroup};

use crate::biome::hex_color_to_linear;
use crate::heightmap::{HeightmapMesh, HeightmapVertex};
use crate::mesh::catmull_rom_open_alpha;

/// One subgroup's style, in linear RGBA (group opacity baked in alpha).
struct RouteStyle {
    color: [f32; 4],
    width: f32,
    /// `[on, off]` dash pattern in world units.
    dash: [f32; 2],
    alpha: f32,
    cap: LineCap,
}

fn style_of(group: RouteGroup) -> RouteStyle {
    let styled = |hex: &str, width: f32, dash: [f32; 2], alpha: f32, cap: LineCap| RouteStyle {
        color: {
            let mut c = hex_color_to_linear(hex);
            c[3] = 0.9; // FMG group opacity
            c
        },
        width,
        dash,
        alpha,
        cap,
    };
    match group {
        RouteGroup::Roads => styled("#d06324", 0.7, [2.0, 2.0], 0.1, LineCap::Butt),
        RouteGroup::Trails => styled("#d06324", 0.25, [0.8, 1.6], 0.1, LineCap::Butt),
        RouteGroup::Searoutes => styled("#ffffff", 0.35, [1.0, 2.0], 0.5, LineCap::Round),
    }
}

/// Tessellated stroke meshes per route group (all alpha-blended).
pub struct RouteMeshes {
    pub roads: HeightmapMesh,
    pub trails: HeightmapMesh,
    pub searoutes: HeightmapMesh,
}

struct StrokeColorCtor([f32; 4]);

impl StrokeVertexConstructor<HeightmapVertex> for StrokeColorCtor {
    fn new_vertex(&mut self, vertex: lyon::tessellation::StrokeVertex<'_, '_>) -> HeightmapVertex {
        let p = vertex.position();
        HeightmapVertex {
            pos: [p.x, p.y],
            color: self.0,
        }
    }
}

/// Builds the three route group meshes.
pub fn build_route_group_meshes(routes: &[Route]) -> RouteMeshes {
    let mut roads = empty();
    let mut trails = empty();
    let mut searoutes = empty();
    let mut tess = StrokeTessellator::new();

    for route in routes {
        if route.points.len() < 2 {
            continue; // FMG skips routes without points / with < 2
        }
        let style = style_of(route.group);
        let target = match route.group {
            RouteGroup::Roads => &mut roads,
            RouteGroup::Trails => &mut trails,
            RouteGroup::Searoutes => &mut searoutes,
        };

        let raw: Vec<[f32; 2]> = route.points.iter().map(|p| [p[0], p[1]]).collect();
        // `curveCatmullRom.alpha(...)`; samples rounded to 1 decimal like
        // FMG's `round(lineGen(points), 1)`.
        let curved = catmull_rom_open_alpha(&raw, style.alpha, 6);
        let curved: Vec<[f32; 2]> = curved
            .iter()
            .map(|p| [(p[0] * 10.0).round() / 10.0, (p[1] * 10.0).round() / 10.0])
            .collect();

        for seg in dash_segments(&curved, style.dash) {
            let mut builder = lyon::path::Path::builder();
            builder.begin(lyon::geom::point(seg[0][0], seg[0][1]));
            for p in seg.iter().skip(1) {
                builder.line_to(lyon::geom::point(p[0], p[1]));
            }
            builder.end(false);
            let path = builder.build();

            let mut mesh: VertexBuffers<HeightmapVertex, u32> = VertexBuffers::new();
            let opts = StrokeOptions::default()
                .with_line_width(style.width)
                .with_line_join(LineJoin::Round)
                .with_line_cap(style.cap);
            if tess
                .tessellate_path(
                    &path,
                    &opts,
                    &mut BuffersBuilder::new(&mut mesh, StrokeColorCtor(style.color)),
                )
                .is_ok()
            {
                append(target, mesh);
            }
        }
    }

    for m in [&mut roads, &mut trails, &mut searoutes] {
        if !m.bounds_min.iter().all(|v| v.is_finite()) {
            m.bounds_min = [0.0; 2];
            m.bounds_max = [0.0; 2];
        }
    }
    RouteMeshes {
        roads,
        trails,
        searoutes,
    }
}

/// Splits a polyline into `dash[0]`-long "on" runs separated by `dash[1]`
/// gaps (SVG `stroke-dasharray: on off`).
fn dash_segments(pts: &[[f32; 2]], dash: [f32; 2]) -> Vec<Vec<[f32; 2]>> {
    let mut segments = Vec::new();
    if pts.len() < 2 {
        return segments;
    }
    let mut current: Vec<[f32; 2]> = vec![pts[0]];
    let mut on = true;
    let mut remaining = dash[0];
    for pair in pts.windows(2) {
        let b = pair[1];
        let mut seg_len = ((b[0] - pair[0][0]).powi(2) + (b[1] - pair[0][1]).powi(2)).sqrt();
        let mut cursor = pair[0];
        while seg_len > 1e-9 {
            let step = seg_len.min(remaining);
            let t = step / seg_len;
            let next = [
                cursor[0] + (b[0] - cursor[0]) * t,
                cursor[1] + (b[1] - cursor[1]) * t,
            ];
            if on {
                current.push(next);
            }
            remaining -= step;
            seg_len -= step;
            cursor = next;
            if remaining <= 1e-9 {
                if on && current.len() >= 2 {
                    segments.push(current.clone());
                }
                // Both transitions restart the run at the cursor.
                current.clear();
                current.push(cursor);
                on = !on;
                remaining = if on { dash[0] } else { dash[1] };
            }
        }
    }
    if on && current.len() >= 2 {
        segments.push(current);
    }
    segments
}

fn empty() -> HeightmapMesh {
    HeightmapMesh {
        vertices: Vec::new(),
        indices: Vec::new(),
        bounds_min: [f32::INFINITY; 2],
        bounds_max: [f32::NEG_INFINITY; 2],
    }
}

fn append(target: &mut HeightmapMesh, mesh: VertexBuffers<HeightmapVertex, u32>) {
    let base = target.vertices.len() as u32;
    let start = target.vertices.len();
    target.vertices.extend(mesh.vertices);
    target
        .indices
        .extend(mesh.indices.iter().map(|&i| i + base));
    for v in &target.vertices[start..] {
        target.bounds_min[0] = target.bounds_min[0].min(v.pos[0]);
        target.bounds_min[1] = target.bounds_min[1].min(v.pos[1]);
        target.bounds_max[0] = target.bounds_max[0].max(v.pos[0]);
        target.bounds_max[1] = target.bounds_max[1].max(v.pos[1]);
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn dash_splits_into_on_runs() {
        // Straight line of length 10, dash [2, 2] → runs at [0,2], [4,6], [8,10].
        let pts: Vec<[f32; 2]> = (0..=10).map(|x| [x as f32, 0.0]).collect();
        let runs = dash_segments(&pts, [2.0, 2.0]);
        assert_eq!(runs.len(), 3, "{runs:?}");
        assert!(
            (runs[0][0][0] - 0.0).abs() < 1e-5 && (runs[0].last().unwrap()[0] - 2.0).abs() < 1e-5
        );
        assert!(
            (runs[1][0][0] - 4.0).abs() < 1e-5 && (runs[1].last().unwrap()[0] - 6.0).abs() < 1e-5
        );
        assert!(
            (runs[2][0][0] - 8.0).abs() < 1e-5 && (runs[2].last().unwrap()[0] - 10.0).abs() < 1e-5
        );
        // Total drawn length = 6 (three 2-unit runs).
        let total: f32 = runs
            .iter()
            .map(|r| {
                r.windows(2)
                    .map(|w| (w[1][0] - w[0][0]).abs() + (w[1][1] - w[0][1]).abs())
                    .sum::<f32>()
            })
            .sum();
        assert!((total - 6.0).abs() < 1e-4);
    }

    #[test]
    fn subgroup_styles_match_fmg_defaults() {
        let roads = style_of(RouteGroup::Roads);
        assert_eq!(roads.width, 0.7);
        assert_eq!(roads.dash, [2.0, 2.0]);
        assert!((roads.color[3] - 0.9).abs() < 1e-6);
        // #d06324: orange → linear red dominant.
        assert!(roads.color[0] > roads.color[2]);

        let trails = style_of(RouteGroup::Trails);
        assert_eq!(trails.width, 0.25);
        assert_eq!(trails.dash, [0.8, 1.6]);

        let sea = style_of(RouteGroup::Searoutes);
        assert_eq!(sea.width, 0.35);
        assert_eq!(sea.dash, [1.0, 2.0]);
        assert!(matches!(sea.cap, LineCap::Round));
        // White stroke: all channels equal and bright.
        assert!((sea.color[0] - sea.color[2]).abs() < 1e-6 && sea.color[0] > 0.9);
        assert!((sea.alpha - 0.5).abs() < 1e-6);
    }
}
