[package]
name = "vor-sim"
version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
edition = "2021"
description = "Motor de simulación procedural de Voronia: heightmap, hidrología, clima, biomas, culturas, estados, religiones, rutas."

[lib]
path = "src/lib.rs"
